src/TipsAndTricks/TatBlog.WebApp/Areas/Admin/Controllers/AuthorsController.cs
using MapsterMapper;
using Microsoft.AspNetCore.Mvc;
using TatBlog.Core.Constants;
using TatBlog.Services.Blogs;
using TatBlog.WebApp.Areas.Admin.Models;

namespace TatBlog.WebApp.Areas.Admin.Controllers
{
    public class AuthorsController : Controller
    {

        private readonly IBlogRepository _blogRepository;
        private readonly IAuthorRepository _authorRepository;
    

        public AuthorsController(IBlogRepository blogRepository, IAuthorRepository authorRepository)
        {
            _blogRepository = blogRepository;
            _authorRepository = authorRepository;
        }

        public async Task<IActionResult> Index(AuthorFilterModel model)
        {
            var authorQuery = new AuthorQuery()
            {
                Keyword = model.Keyword,
            };

            ViewBag.AuthorsList = await _authorRepository.GetAuthor_KeywordAsync(authorQuery);

            return View(model);
        }

        public async Task<IActionResult> DeleteAuthor(int id)
        {
            await _authorRepository.DeleteAuthorAsync(id);
            return RedirectToAction("Index");
        }
    }
}

src/TipsAndTricks/TatBlog.WebApp/Areas/Admin/Controllers/CommentsController.cs
using Microsoft.AspNetCore.Mvc;

namespace TatBlog.WebApp.Areas.Admin.Controllers
{
    public class CommentsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/TipsAndTricks/TatBlog.WebApp/Areas/Admin/Controllers/PostsController.cs
using FluentValidation;
using FluentValidation.AspNetCore;
using MapsterMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.VisualBasic;
using TatBlog.Core.Constants;
using TatBlog.Core.Entities;
using TatBlog.Services.Blogs;
using TatBlog.Services.Media;
using TatBlog.WebApp.Areas.Admin.Models;

namespace TatBlog.WebApp.Areas.Admin.Controllers
{
    public class PostsController : Controller
    {

        private readonly IBlogRepository _blogRepository;
        private readonly IMapper _mapper;
        private readonly IMediaManager _mediaManager;
        private readonly IAuthorRepository _authorRepository;
        private readonly ILogger<PostsController> _logger;
        private readonly IValidator<PostEditModel> _postValidator;
        private readonly ICategoryRepository _categoryRepository;

        public PostsController(IBlogRepository blogRepository, IMapper mapper, IMediaManager mediaManager, ILogger<PostsController> logger, IValidator<PostEditModel> postValidator, IAuthorRepository authorRepository, ICategoryRepository categoryRepository)
        {
            _postValidator = postValidator;
            _authorRepository = authorRepository;
            _blogRepository = blogRepository;
            _mapper = mapper;
            _mediaManager = mediaManager;
            _logger = logger;
            _categoryRepository = categoryRepository;
        }
        // Phương thức gán giá trị cho các thuộc tính của 1 đối tượng PostFilterModel

        private async Task PopulatedPostFilterModelAsync(PostFilterModel model)
        {
            var authors = await _authorRepository.GetAuthorsAsync();
            var categories = await _categoryRepository.GetCategoriesAsync();

            model.AuthorList = authors.Select(a => new SelectListItem()
            {
                Text = a.FullName,
                Value = a.Id.ToString()
            });

            model.CategoryLíst = categories.Select(c => new SelectListItem() { Text = c.Name, Value = c.Id.ToString() });
        }

        private async Task PopulatedPostEditModelAsync(PostEditModel model)
        {
            var authors = await _authorRepository.GetAuthorsAsync();

            var categories = await _categoryRepository.GetCategoriesAsync();

            model.AuthorList = authors.Select(a => new SelectListItem()
            {
                Text = a.FullName,
                Value = a.Id.ToString()
            });
            model.CategoryList = categories.Select(c => new SelectListItem()
            {
                Text = c.Name,
                Value = c.Id.ToString()
            });
        }

        public async Task<IActionResult> Index(PostFilterModel model,
            [FromQuery(Name = "p")] int PageNumber = 1,
            [FromQuery(Name = "ps")] int PageSize = 10)
        {
            _logger.LogInformation("Tạo điều kiện truy vấn");

            var postQuery = _mapper.Map<PostQuery>(model);

            _logger.LogInformation("Lấy dan sách bài viết từ CSDL");
            ViewBag.PostsList = await _blogRepository.GetPagedPostAsync(postQuery, PageNumber, PageSize);
            _logger.LogInformation("Chuẩn bị dữ liệu cho ViewModel");
            ViewBag.PostQuery = postQuery;
            await PopulatedPostFilterModelAsync(model);
            return View(model);
        }

        public async Task<IActionResult> DeletePost(int id = 0)
        {
            await _blogRepository.DeletePostAsync(id);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> TogglePublished(int id = 0)
        {
            await _blogRepository.TogglePublishedFlagAsync(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id = 0)
        {
            var post = id > 0
                ? await _blogRepository.GetPostByIdAsync(id, true)
                : null;

            var model = post == null
                ? new PostEditModel()
                : _mapper.Map<PostEditModel>(post);

            await PopulatedPostEditModelAsync(model);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(PostEditModel model)
        {

            var validationResult = await _postValidator.ValidateAsync(model);
            if (validationResult.IsValid)
            {
                validationResult.AddToModelState(ModelState);
            }


            if (!ModelState.IsValid)
            {
                await PopulatedPostEditModelAsync(model);
                return View(model);
            }

            var post = model.Id > 0
                ? await _blogRepository.GetPostByIdAsync(model.Id)
                : null;

            if (post == null)
            {
                post = _mapper.Map<Post>(model);

                post.Id = 0;
                post.PostedDate = DateTime.Now;
            }
            else
            {
                _mapper.Map(model, post);

                post.Category = null;
                post.ModifiedDate = DateTime.Now;
            }

            if (model.ImageFile?.Length > 0)
            {
                var newImagePath = await _mediaManager.SaveFileAsync(
                    model.ImageFile.OpenReadStream(),
                    model.ImageFile.FileName,
                    model.ImageFile.ContentType);
                if (!string.IsNullOrWhiteSpace(newImagePath))
                {
                    await _mediaManager.DeleteFileAsync(post.ImageUrl);
                    post.ImageUrl = newImagePath;
                }
            }

            await _blogRepository.CreateOrUpdatePostAsync(post, model.GetSelectedTags());

            return RedirectToAction(nameof(Index));

        }
        [HttpPost]
        public async Task<IActionResult> VerifyPostSlug(int id, string urlSlug)
        {
            var slugExisted = await _blogRepository.IsPostSlugExistedAsync(id, urlSlug);

            return slugExisted ? Json($"Slug '{urlSlug}' đã được sử dụng") : Json(true);
        }
    }
}

src/TipsAndTricks/TatBlog.WebApp/Areas/Admin/Controllers/TagsController.cs
using Microsoft.AspNetCore.Mvc;
using TatBlog.Core.Constants;
using TatBlog.Services.Blogs;
using TatBlog.WebApp.Areas.Admin.Models;

namespace TatBlog.WebApp.Areas.Admin.Controllers
{
    public class TagsController: Controller
    {
        private readonly IBlogRepository _blogRepository;
        private readonly ITagRepository _tagRepository;


        public TagsController(IBlogRepository blogRepository, ITagRepository tagRepository)
        {
            _blogRepository = blogRepository;
            _tagRepository = tagRepository;
        }

        public async Task<IActionResult> Index(TagFilterModel model)
        {
            var tagQuery = new TagQuery()
            {
                Keyword = model.Keyword
            };
            ViewBag.TagsList= await _tagRepository.GetTags_KeywordAsync(tagQuery);
            return View(model);
        }

        public async Task<IActionResult> DeleteTag(int id)
        {
            await _tagRepository.DeleteTagAsync(id);

            return RedirectToAction("Index");
        }
    }
}

src/TipsAndTricks/TatBlog.WebApp/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["PageTitle"]-Tis & Tricks Blog</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="~/css/main.css" asp-append-version = "true"/>

    @await RenderSectionAsync("styles", required: false)
</head>
<body>
        <partial name="_NavBar"/>

        <div class="container-fluid">
            @RenderBody()
        </div>

    <footer class="border-top footer text-muted">
        <div class="container-fluid text-center">
            &copy; 2023 - Tips & Tricks Blog
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/main.js" asp-append-version="true"></script>

    @await RenderSectionAsync("scripts", required: false)
</body>
</html>

src/TipsAndTricks/TatBlog.WebApp/Areas/Admin/Views/Shared/_NavBar.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
        <div class="container-fluid">
            <a class="navbar-brand"
                asp-area="Admin"
                asp-controller="Dashboard"
                asp-action="Index">
                Tips & Tricks
            </a>
            <button class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-flex-grow-1">

                    <li class="nav-item">
                        <a class="nav-link text-dark"
                            asp-area="Admin"
                            asp-controller="Categories"
                            asp-action="Index"
                            title="Xem danh sách chủ đề">
                            Chủ đề
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link text-dark"
                            asp-area="Admin"
                            asp-controller="Authors"
                            asp-action="Index"
                            title="Xem danh sách Tác giả">
                            Tác giả
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link text-dark"
                            asp-area="Admin"
                            asp-controller="Tags"
                            asp-action="Index"
                            title="Xem danh sách Thẻ/Từ khóa">
                            Thẻ
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link text-dark"
                            asp-area="Admin"
                            asp-controller="Posts"
                            asp-action="Index"
                            title="Xem danh sách Bài viết">
                            Bài viết
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link text-dark"
                            asp-area="Admin"
                            asp-controller="Comments"
                            asp-action="Index"
                            title="Xem danh sách bình luận ">
                            Bình luận
                        </a>
                    </li>
                </ul>
            </div>

        </div>
    </nav>
</header>